- name: This will show the Use of Comparision Operators 
  hosts: localhost
  gather_facts: false  

  vars:
    a: "HELLO"
    d: "hello"
    b: 10
    c: 20

  tasks:
    - name: Operations on Variables
      debug:
        msg:
        - "The value of b is : {{ a }}, and value of c is : {{ c }}"
        - "Is b greater than c : {{ b > c }}"
        - "Is b less than c : {{ b < c }}"
        - "Is b equals to c : {{ b == c }}"
        - "Is b greater than or equal to c : {{ b >= c }}"
        - "Is b less than or equal to c : {{ b <= c }}"
        - "Below comparision is for string"
        - "The value of a is : {{ a }}, and value of d is : {{ d }}"
        - "Is a greater than d : {{ a > d }}"
        - "Is a less than d : {{ a < d }}"
        - "Is a equals to d : {{ a == d }}"
        - "Is a not equal to d : {{ a != d }}"
        - "Is a equals to d : {{ a|lower == d }}"
