- name: This will show the Use of Logical Operators
  hosts: localhost
  gather_facts: false  

  vars:
    x: true
    y: false
    z: false
    m: true

  tasks:
    - name: Operations on variables
      debug: 
        msg:
          - "x and y : {{ x and y }}"
          - "x and m : {{ x and m }}"
          - "x or m : {{ x or m }}"
          - "y or z : {{ y or z}}"
          - "x and y or m: {{ x and y or m}}"
  
