- name: This will show the Use of Comparision Operators 
  hosts: localhost
  gather_facts: false  

  vars:
    a: "HELLO"
    d: "hello"
    b: 10
    c: 20
    e: [1,5,9,10,15,109]
    x: /ansible/operators_statement
    y: /ansible/operators_statement/comparision_operator.yml

  tasks:
    - name: Operations on Variables
      debug:
        msg:
        - "The List is - {{ e }}, value of c is - {{ c }} and value of b is - {{ b }}"
        - "Is b member of e : {{ b in e }}"
        - "Is c member of e : {{ c in e }}"
        - "Is 25 member of e : {{ 25 in e }}"
        - "Is c not a member of e : {{ c not in e }}"


    - name: Tests Operators
      debug:
        msg:
        - "a is defined?   {{ a is defined }}"
        - "c is defined?   {{ c is defined }}"
        - "a is Upper?   {{ a is upper }}"
        - "b is Lower?   {{ b is lower }}"
        - "e is String?   {{ e is string }}"
        - "y is file:   {{ y is file }}"
        - "x is directory: {{ x is directory }}"
        - "y is directory: {{ y is directory }}"
