version: "3.8"

services:
  ansible:
    build: ./ansible-dockerfile
    command: tail -F /dev/null
    container_name: ansible
    hostname: ansible
    volumes:
      - ./ansible:/ansible
      - ansible-home:/home/ansible
      - ansible-root:/root
    networks:
      - ansible-net
  
  server_1:
    build: ./servers-dockerfile
    container_name: server_1
    hostname: server_1
    volumes:
      - ertan-home:/home/ertan
      - server_1-root:/root
    networks:
      - ansible-net

  server_2:
    build: ./servers-dockerfile
    container_name: server_2
    hostname: server_2
    volumes:
      - ertan-home:/home/ertan
      - server_2-root:/root
    networks:
      - ansible-net
      
volumes:
  ansible-home:
  ansible-root:
  ertan-home:
  server_1-root:
  server_2-root:

networks:
  ansible-net:
    name: ansible-net