- name: Installing WebServer 
  hosts: all
  remote_user: root
  vars:
    ansible_ssh_private_key_file: /root/.ssh/id_rsa

  tasks:
    - name: Ensure Apache is at the Latest Version
      apt:
        name: apache2
        state: present 
      notify:
        - Ensure Apache is Running 
        - Ensure Apache is Restart 
      
  handlers:
    - name: Ensure Apache is Running
      service: 
        name: apache2
        state: started

    - name: Ensure Apache is Restart
      service: 
        name: apache2
        state: restarted
      
