- name: Installing WebServer 
  hosts: all
  remote_user: root
  vars:
    ansible_ssh_private_key_file: /root/.ssh/id_rsa

  tasks:
    - name: Ensure Apache is at the Latest Version
      apt:
        name: apache2
        state: latest  
      register: apache2_installation_status     
      

    - name: Ensure Apache is Running
      service: 
        name: apache2
        state: started
      when: apache2_installation_status.changed == True
