- name: Ansible Delegate_to examples 
  hosts: all
  remote_user: root
  vars:
    ansible_ssh_private_key_file: /root/.ssh/id_rsa
    tmplog: /tmp/connection.log

  tasks:
  - name: create tmplog
    shell: test ! -f {{ tmplog }} && touch {{ tmplog }}
    failed_when: false
  
  - name: delegate_to
    shell: echo "delegate_to . {{ inventory_hostname }} $(hostname) ." >> {{ tmplog }}
    delegate_to: ec2-13-59-156-142.us-east-2.compute.amazonaws.com
