- name: This is to Display Arithmetic Operations on Variables 
  hosts: localhost
  gather_facts: false  

  vars:
    a: 10
    b: "{{a*10}}"

  vars_prompt:
    - name: x
      prompt: Please enter value of x
      private: no

    - name: y
      prompt: Please enter value of y
      private: no

  tasks:
    - name: Operations on Variables
      debug:
        msg: 
        - "value of a is : {{a}}"
        - "value of b is : {{b}}"
        - "Addition of User Defined Values x, y is : {{x + y}}"
        - "Addition of User Defined Values x, y is : {{x|int + y|int}}"
        - "Multiply of User Defined Values x, y is : {{x|int * y|int}}"
        
