- name: This will show the use of include task
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Play 1 - Task 1
      debug:
        msg: "Play 1 - Task 1"
    - include_tasks: tasks-1.yml
    
    # - name: Include tasks from tasks-1.yml
    #   include_tasks: tasks-1.yml
      
